# Generated by Django 3.2.9 on 2021-11-22 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=6)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=6)),
                ('floor_num', models.IntegerField()),
                ('location_description', models.TextField()),
                ('accepted_categories', models.CharField(blank=True, choices=[('Category1', 'Category1'), ('Category2', 'Category2'), ('Category3', 'Category3')], max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sample_image', models.ImageField(blank=True, null=True, upload_to='media/sample_images/')),
            ],
        ),
        migrations.CreateModel(
            name='DWUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('nbr_of_images', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Building_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_image', models.ImageField(blank=True, null=True, upload_to='media/building_images/')),
                ('buildling', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Components.building')),
            ],
        ),
        migrations.CreateModel(
            name='Bin_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_images', models.ImageField(blank=True, null=True, upload_to='media/bin_images/')),
                ('bin', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Components.bin')),
            ],
        ),
        migrations.AddField(
            model_name='bin',
            name='building_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Components.building'),
        ),
    ]
