# Generated by Django 3.2.9 on 2021-12-18 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=6)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=6)),
                ('floor_num', models.IntegerField()),
                ('location_description', models.TextField()),
                ('accepted_categories', models.CharField(blank=True, choices=[('C1', 'Category1'), ('C2', 'Category2'), ('C3', 'Category3')], max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('category_sample_image', models.ImageField(blank=True, null=True, upload_to='sample_images/')),
            ],
        ),
        migrations.CreateModel(
            name='DWUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('nbr_of_images', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trash_Accepted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_image', models.ImageField(blank=True, null=True, upload_to='accepted_trash_images/')),
                ('name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Components.category', to_field='name')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryInstructions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions', models.TextField()),
                ('category', models.ManyToManyField(to='Components.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Building_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_image', models.ImageField(blank=True, null=True, upload_to='building_images/')),
                ('building', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Components.building')),
            ],
        ),
        migrations.CreateModel(
            name='Bin_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_images', models.ImageField(blank=True, null=True, upload_to='bin_images/')),
                ('bin_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Components.bin')),
            ],
        ),
        migrations.AddField(
            model_name='bin',
            name='building_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Components.building'),
        ),
    ]
