# Generated by Django 3.2.9 on 2021-11-22 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Components', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bin_images',
            old_name='bin',
            new_name='bin_id',
        ),
    ]
