# Generated by Django 3.2.9 on 2021-11-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Components', '0002_rename_bin_bin_images_bin_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trash_Accepted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_image', models.ImageField(blank=True, null=True, upload_to='accepted_trash_images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='sample_image',
        ),
        migrations.AddField(
            model_name='category',
            name='category_sample_image',
            field=models.ImageField(blank=True, null=True, upload_to='sample_images/'),
        ),
        migrations.AlterField(
            model_name='bin',
            name='accepted_categories',
            field=models.CharField(blank=True, choices=[('C1', 'Category1'), ('C2', 'Category2'), ('C3', 'Category3')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bin_images',
            name='bin_images',
            field=models.ImageField(blank=True, null=True, upload_to='bin_images/'),
        ),
        migrations.AlterField(
            model_name='building_images',
            name='building_image',
            field=models.ImageField(blank=True, null=True, upload_to='building_images/'),
        ),
    ]
