# Generated by Django 3.2.9 on 2021-12-18 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Components', '0003_auto_20211126_2007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building_images',
            old_name='buildling',
            new_name='building',
        ),
        migrations.AddField(
            model_name='trash_accepted',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Components.category', to_field='name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='CategoryInstructions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions', models.TextField()),
                ('category', models.ManyToManyField(to='Components.Category')),
            ],
        ),
    ]
